name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  command:
    description: 'The Command to execute\nValid commands are: \n- ack\n- secure\n- rewire\n- comment'
    required: true
  ado_pat:
    description: 'The Personal Access token used to call the API \nThis action required org admin previleges'
    required: true
  github_token:
    description: 'The Personal Access token used to call the API \nThis action required org admin previleges'
    required: true
  issue_body_json:
    description: 'The JSON from the parsed issue body'
    required: true  
outputs:
  status: # output will be available to future steps
    description: 'The Status of a particular request'
runs:
  using: 'node16'
  main: 'dist/index.js'
