name: Rewire ADO pipelines to use a Standard GitHub App service connection in a project
description: This is an issue ops based interface to Rewire ADO pipelines to use a Standard GitHub App service connection.
title: "Share Motorola Standard ADO service connection with a project"
labels: ["issueops-share-ado"]
body:
- type: markdown
  attributes:
    value: "## Rewire ADO pipelines to use a Standard GitHub App service connection in a project."
- type: markdown
  attributes:
    value: |
      This is an issue to Rewire ADO pipelines in an ADO project to use a Standard GitHub App service connection.
      
      If you have any questions, please reach out to @decyjphr.

      Once the issue is created, at any time, you can type the following commands as issue comment to interact:
      
      `ack` - Acknowledge the request
      `validate` - Validate the request
      `share` - Share the Shared Service Connection
      `rewire` - Rewire the project
      `approve` - Approve the request

- type: input
  id: destination-project
  attributes:
    label: ">>Destination_Project<<"
    description: "Enter the Project where the connection must be shared."
  validations:
    required: true
    

      
