name: Test Action

on:
  issues:
    types: [labeled]    
  issue_comment:
jobs:
  test:
    name: Test Action
    if: contains(github.event.issue.labels.*.name, 'issueops-share-ado')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - id: parse
        name: Run Issue form parser
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<' 
      - id: issueinput
        name: Parse Issue Input to get the type
        uses: actions/github-script@v5
        env:
          payload: ${{ steps.parse.outputs.payload }}
          ado_pat: ${{ secrets.ADO_PAT }}
          ado_org: ${{ secrets.ADO_ORG }}
          ado_shared_project: ${{ secrets.ADO_SHARED_PROJECT }}
          ado_shared_service_connection: ${{ secrets.ADO_SHARED_SERVICE_CONNECTION }}
        with:
          script: |
            const {payload} = process.env
            console.log(JSON.stringify(payload,null,2))
            const input = JSON.parse(payload)
            input.adoToken = process.env.ado_pat
            input.adoOrg = process.env.ado_org
            input.adoSharedProject = process.env.ado_shared_project
            input.adoSharedServiceConnection = process.env.ado_shared_service_connection
            core.setOutput('payload', input);

      - id: issue-labeled
        if: github.event_name == 'issues'
        uses: ./
        with:
          ado_pat: ${{ secrets.ADO_PAT }}
          ado_org: ${{ secrets.ADO_ORG }}
          ado_shared_project: ${{ secrets.ADO_SHARED_PROJECT }}
          ado_shared_service_connection: ${{ secrets.ADO_SHARED_SERVICE_CONNECTION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_body_json: ${{ steps.parse.outputs.payload }}
          command: 'ack'
      
      - id: issue-comment-input
        if: github.event_name == 'issue_comment'
        uses: ./
        with:
          ado_pat: ${{ secrets.ADO_PAT }}
          ado_org: ${{ secrets.ADO_ORG }}
          ado_shared_project: ${{ secrets.ADO_SHARED_PROJECT }}
          ado_shared_service_connection: ${{ secrets.ADO_SHARED_SERVICE_CONNECTION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_body_json: ${{ steps.parse.outputs.payload }}
          command: ${{ github.event.comment.body }}

